package model;
// Generated Nov 20, 2023 10:56:32 AM by Hibernate Tools 4.3.1



/**
 * Mycustomer generated by hbm2java
 */
public class Mycustomer  implements java.io.Serializable {


     private String id;
     private Double balance;
     private Integer password;

    public Mycustomer() {
    }

	
    public Mycustomer(String id) {
        this.id = id;
    }
    public Mycustomer(String id, Double balance, Integer password) {
       this.id = id;
       this.balance = balance;
       this.password = password;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public Integer getPassword() {
        return this.password;
    }
    
    public void setPassword(Integer password) {
        this.password = password;
    }




}


